#!/bin/bash
# ==================================================================
# FILE     abookFind
# MACHINE  all
# INFO     
#
# DATE     19.07.2016
# OWNER    Bischofberger
# ==================================================================
# TODO: - GROUP as an argument
#       - collect several groups

ADDRESSBOOK="$HOME/.abook/addressbook"
GROUP="BGB15a"
BLOCKLIST=()
COL_EMAIL_ADR=""

die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

# read blocks
{
  read -r block    # First line only
  while read -r; do
    if [[ $REPLY =~ ^$ ]]; then
      # Do what you like with the contents 
      # $block here, then ...
      BLOCKLIST+=("$block")
      block=""
    else
      block+="$REPLY"$'\n'  # insert a new line (bash and zsh only)
    fi
  done
} < $ADDRESSBOOK

BLOCKLIST=("${BLOCKLIST[@]:1,3}") #removed the 1st 3 elements

for block in "${BLOCKLIST[@]}" ; do
  echo "$block" | awk -F "=|," '$1 == "group" && /'$GROUP'/ {exit 1}'

  HAS_GROUP=$?  # $? is the exit status of the last statement

  if [ $HAS_GROUP -eq 1 ] ; then
    COL_EMAIL_ADR+=`echo "$block" | awk -F "=" '$1 == "email" {print $2", "}'`
  fi
done

echo -n "$COL_EMAIL_ADR" | xsel --primary -i
echo -n "$COL_EMAIL_ADR" | xsel --clipboard -i
