#!/bin/bash
# ==================================================================
# FILE     backup
# MACHINE  desktop
# INFO     rsnapshot wrapper
#
# DATE     18.04.2022
# OWNER    Bischofberger
# ==================================================================

CONFIGS="/home/desktop/Scripts/data"

rsnapshot -c "$CONFIGS/rsnapshot_local.conf" "alpha"
