#!/bin/bash
# ==================================================================
# FILE     backup
# MACHINE  all
# INFO     rsnapshot wrapper
#
# DATE     18.03.2018
# OWNER    Bischofberger
# ==================================================================

CONFIGS="$HOME/Scripts/data"

# local
CONFIGFILE_LOCAL_QUICK="$CONFIGS/rsnapshot_local_quick.conf"
CONFIGFILE_LOCAL_FULL="$CONFIGS/rsnapshot_local_full.conf"

# bmz
EXTERNAL="/run/media/desktop/Other/Backup_webdav_BMZ"
CONFIGFILE_BMZ="$CONFIGS/rsnapshot_bmz.conf"
STATUSFILE="$EXTERNAL/backup-statusfile.txt"
WEEKLY_LIMIT="4"
MONTHLY_LIMIT="12"


die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

backitup() {
  sudo rsnapshot -c "$1" "$2"
}

privatebackup() {
  echo "Enter backup option:"
  echo -e "1\tquick\n2\tfull"
  read op
  case "$op" in
    "1")
      backitup "$CONFIGFILE_LOCAL_QUICK" "alpha" || return 1  # 0 = true, 1 = false
      ;;
    "2")
      backitup "$CONFIGFILE_LOCAL_FULL" "alpha" || return 1  # 0 = false, 1 = false
      ;;
    *)
      die "unknown parameter '$op'"
      ;;
  esac
}

create_statusfile() {
  if [ ! -f "$STATUSFILE" ] ; then
    echo -n "There is no statusfile. Creating one..."
    touch $STATUSFILE
    cat > "$STATUSFILE" <<'EOF'
# ==================================================================
# FILE     backup-statusfile
# MACHINE  all
# INFO     handle rsnapshot backup intervals (BMZ webdav)
#
# DATE     
# OWNER    Bischofberger
# ==================================================================

# number of backups made:
BMZ_WEEKLY=0
BMZ_MONTHLY=0
EOF
    echo "done."
  fi
}

update_statusfile() {
  sed -i s/^BMZ_WEEKLY\=.*/BMZ_WEEKLY\="$BMZ_WEEKLY"/ $STATUSFILE
  sed -i s/^BMZ_MONTHLY\=.*/BMZ_MONTHLY\="$BMZ_MONTHLY"/ $STATUSFILE
}

bmzbackup() {
  cd "$HOME"
  mount webdav

  if [ ! -d "$EXTERNAL" ] ; then
    die "mount external HD"
  fi

  create_statusfile
  source "$STATUSFILE"

  backitup "$CONFIGFILE_BMZ" "weekly" || return 1  # 0 = true, 1 = false
  ((++BMZ_WEEKLY))

  if [[ "$BMZ_WEEKLY" == "$WEEKLY_LIMIT" ]] ; then
    backitup "$CONFIGFILE_BMZ" "monthly" || return 1  # 0 = true, 1 = false
    ((++BMZ_MONTHLY))
    BMZ_WEEKLY=0
  fi

  if [[ "$BMZ_MONTHLY" == "$MONTHLY_LIMIT" ]] ; then
    backitup "$CONFIGFILE_BMZ" "yearly" || return 1  # 0 = true, 1 = false
    BMZ_MONTHLY=0
  fi

  update_statusfile
}


# main -----------------------------------
echo "Enter backup option:"
echo -e "1\tprivate\n2\tbmz"

read number

case "$number" in
  "1")
    privatebackup
    exit 0
    ;;
  "2")
    bmzbackup
    exit 0
    ;;
  *)
    die "unknown parameter '$number'"
    ;;
esac
