#!/bin/bash
# ==================================================================
# FILE     beamer
# MACHINE  all
# INFO     handles resolution in multi-monitor setup with dwm
#					 when mirroring is involved
#
# DATE     16.03.2016
# OWNER    Bischofberger
# ==================================================================
# TODO: option for getting out of dual mode

# Auto:
# 1. Auflösungen auflisten
# 2. Wähle grösste Beamer-Auflösung
# 3. Vergleiche in internen Auflösungen
#		 3a. Suche erfolgreich (1024x768 oder höher)
#				-> activateDualMode()
#    3b. Suche erfolglos													
#				-> Meldung und check, ob Auflösung grösser als internal
#						-> Falls ja   -> activateDualMode_panning()
#						-> Falls nein -> ???

# Manuell (-m|--manually):
# 1. Auflösungen auflisten
# 2. Beamer-Auflösung eingeben (x, y)
# 3. Panning? eingeben
# Tests fahren:
# Panning ja		-> Auflösung >= Internal? -> Ja, ok, Nein, Abbruch
# Panning Nein	-> Auflösung = InternalMax? -> Ja, ok, Nein, Abbruch

# Force (-f|--force):
# wie manuell, aber ohne Tests


INTERNAL="LVDS"
RES_INT_x="1366"
RES_INT_y="768"
RES_INT_LIST=("1366x768" \
							"1280x720" \
							"1152x768" \
							"1024x768")

EXTERNAL="VGA-0"
RES_EXT_x="1"
RES_EXT_y="1"

die(){
	echo -e "$0: Error: $1" >&2
	exit 1
}

isValidRes(){
	if [[ $1 =~ ^[0-9]+$ ]] && (( $1 > 0 )); then
		return 0  # 0 = true
	else
		return 1  # 1 = false
	fi
}

usage(){
	echo -e "Usage: $0 [OPTION]

Handles dual-monitor setup with suckless dwm.

If no argument is given, automatic setup ist being executed. In automatic mode
the highest possible external resolution will be chosen by default and compared
to the internal resolutions. If there is a match, conventional dual-mode will
be activated. If it is larger than the highest interal resolution, panning mode
will be activated.
Note, that by now (03.2016) there is no proper way to get out of panning mode.
You must kill the Xserver to do so.\n\

-h, --help            Show this help.
-m, --manually        Manually enter desired external monitor resolution.
                      Additional size checks give extra security in this mode.
-f, --force           Same as the \"-m\"-flag but no size checks here.
-d, --deactivate      Get out of dual-mode. (not working properly for panning yet)
"
	}

listAllResolutions(){
	xrandr
}

printResolution(){
	echo "${1}x${2}"
}

getHighestExternalResolution(){
	# awk:	1.) search first line containing $EXTERNAL; set y as 1
	#				2.) skip one line: "next"
	#				3.) print only one line: while y!= 0 print first column ($1), 
	#						set y to 0 right afterwards in order to just print 1 line.
	local res=`xrandr | awk '/'$EXTERNAL'/{y=1; next} y!= 0 {print $1; y=0}'`
	if [ -z "$res" ] ; then
		die "no external resolution detected"
	fi
	RES_EXT_x="$(echo $res | awk -F "x" '{print $1}')"
	RES_EXT_y="$(echo $res | awk -F "x" '{print $2}')"
	if !(isValidRes $RES_EXT_x && isValidRes $RES_EXT_y) ; then
		die "failed to extract external resolution"
	fi
}

#xrandr --output LVDS --mode 1366x768 --fb 1920x1200 --panning 1920x1200* --output VGA-0 --mode 1920x1200 --same-as LVDS
activateDualMode_panning(){
	xrandr	--output $INTERNAL --mode $RES_INT_MAX --fb $RES_EXT --panning $RES_EXT* \
					--output $EXTERNAL --mode $RES_EXT --same-as $INTERNAL
	echo "In order to get out of panning mode, you must kill dwm (Mod1-Shift-q)
				and therefore kill the X-server. (Bug in xrandr, 03.2016)"
}

# für 1024x768
activateDualMode(){
	xrandr --output $EXTERNAL --auto --same-as $INTERNAL --mode `printResolution $RES_EXT_x $RES_EXT_y`
	xrandr --output $INTERNAL --mode `printResolution $RES_EXT_x $RES_EXT_y`
}

# TODO: workaround for getting out of panning...
deactivateDualMode(){
	#xrandr --output $EXTERNAL --primary
	#xrandr --output $INTERNAL --primary
	read -p "Plug out external monitor and press [Enter]."
	xrandr --output $INTERNAL --mode `printResolution $RES_INT_x $RES_INT_y`
	xrandr >/dev/null
	xrandr --auto
}

readDesiredExternalResolution(){
	echo "Enter desired resolution of external: [{X}x{Y}]"
	read res  # local not possible due to "read"
	RES_EXT_x="$(echo $res | awk -F "x" '{print $1}')"
	RES_EXT_y="$(echo $res | awk -F "x" '{print $2}')"
	unset res
	if !(isValidRes $RES_EXT_x && isValidRes $RES_EXT_y) ; then
		die "failed to extract external resolution"
	fi
}

# Test in Funktion scheint nicht zu gehen...
isExternalGreaterThanInternal(){
	if (( "$RES_EXT_x" > "$RES_INT_x" && "$RES_EXT_y" > "$RES_INT_y" )) ; then
		return 0  # 0 = true
	else
		return 1  # 1 = false
	fi
}

isExternalEqualToInternal(){
	for res in "${RES_INT_LIST[@]}" ; do
		local resX="$(echo $res | awk -F "x" '{print $1}')"
		local resY="$(echo $res | awk -F "x" '{print $2}')"
		unset res
		if (( "$resX" == "$RES_EXT_x" && "$resY" == "$RES_EXT_y" )) ; then
			return 0  # 0 = true
		fi
	done
	return 1  # 1 = false
}

usePanning(){
	echo "panning? [y|n]"
	read panning
	case "$panning" in
		"y")
			unset panning
			return 0  # 0 = true
			;;
		"n")
			unset panning
			return 1  # 1 = false
			;;
		*)
			die "unknown parameter '$panning"
			;;
	esac
}

# manually but with some tests
setup_m(){
	listAllResolutions
	readDesiredExternalResolution
	if usePanning ; then
		if isExternalGreaterThanInternal ; then
			activateDualMode_panning
		else
			die "External screen resolution greater than internal. Panning not allowed."
		fi
	else  # no panning
		if isExternalEqualToInternal ; then
			activateDualMode
		else
			die "No common screen resolution found. Try \"-f|-force\"."
		fi
	fi
}

# no tests here
setup_force(){
	listAllResolutions
	readDesiredExternalResolution
	if usePanning ; then
		activateDualMode_panning
	else
		activateDualMode
	fi
}

# fully automatic
setup_a(){
	listAllResolutions
	getHighestExternalResolution
	if isExternalEqualToInternal ; then
		echo -n "Highest external resolution is equal to internal resolution: "
		printResolution $RES_EXT_x $RES_EXT_y
		echo "Activating dual-mode..."
		activateDualMode
	else
		echo "Hightest external resolution (`printResolution $RES_EXT_x $RES_EXT_y`) could not be found in internal list."
		if isExternalGreaterThanInternal ; then
			echo "We are lucky. External resolution is greater than hightest internal."
			echo "Activating dual-mode with panning..."
			activateDualMode_panning
		else
			die "Hightest external resolution (`printResolution $RES_EXT_x $RES_EXT_y`) is smaller than highest internal. No solution yet..."
		fi
	fi
}


# Main ------------------------------------------------

# handle options
while [ -n "$1" ]; do
	case "$1" in
		"-m"|"--manually")
			setup_m
			exit 0
			;;
		"-f"|"--force")
			setup_f
			exit 0
			;;
		"-h"|"--help")
			usage
			exit 0
			;;
		"-d"|"--deactivate")
			deactivateDualMode
			exit 0
			;;
		*)
			echo "usage: $0 [-a|--auto] [-m|--manually] [-f|--force]"
			die "unknown parameter '$1'"
			;;
	esac
done

# if no argument is given do automatic setup
setup_a
exit 0
