#!/bin/bash
# ==================================================================
# FILE     clipswap
# MACHINE  all
# INFO     uses xsel to swap PRIMARY and CLIPBOARD
#
# DATE     14.01.2016
# OWNER    Bischofberger
# ==================================================================

die() {
	echo -e "$0: Error: $1" >&2
	exit 1
}

listContent() {
	echo -e "[[PRIMARY]]------------------------" 
	xsel -p ; echo ""

	echo -e "[[CLIPBOARD]]----------------------"
	xsel -b ; echo ""

	echo -e "[[SECONDARY]]----------------------"
	xsel -s ; echo ""
}

swapThem() {
	# step 1 - copy PRIMARY to SECONDARY
	xsel --primary | xsel --input --secondary
	# step 2 - copy CLIPBOARD to PRIMARY
	xsel --clipboard | xsel --input --primary
	# step 3 - copy SECONDARY (former PRIMARY) to CLIPBOARD
	xsel --secondary | xsel --input --clipboard
	# step 4 - clear SECONDARY
	xsel --clear --secondary
}

clearAll() {
	xsel --clear --primary
	xsel --clear --secondary
	xsel --clear --clipboard
}

# if no argument is given, swap contents of PRIMARY/CLIPBOARD
if [ -z "$1" ] ; then
	swapThem
	exit 0
fi

# various options
case "$1" in
	"-s"|"--show")
		listContent
		exit 0
		;;
	"-c"|"--clear")
		clearAll
		;;
	*)
		die "invalid argument"
		;;
esac
