#!/bin/bash
# ==================================================================
# FILE     copycovers
# MACHINE  all
# INFO     copy all cover.jpg to destination
#
# DATE     21.09.2014
# OWNER    Bischofberger
# ==================================================================


FILE="cover.jpg"
FLACDIR="/home/desktop/Music/flac"
OGGDIR="/home/desktop/Music/ogg"

while read LINE ; do
	if [[ -e $FLACDIR/$LINE/$FILE ]] && [[ ! -e $OGGDIR/$LINE/$FILE ]] ; then
			cp --verbose "$FLACDIR/$LINE/$FILE" "$OGGDIR/$LINE/$FILE"
	fi
done < albumlist_nonumbr.tmp
