#!/bin/bash
# ==================================================================
# FILE     downsizeAlbumCovers
# MACHINE  all
# INFO     Resize all .jpg/.jpeg/.png to max 1024 pixels width.
#
#          Copy this script into Music/ folder in order to downsize
#          all cover.jpg files to a reasonable filesize.
#
# DATE     26.11.2017
# OWNER    Bischofberger
# ==================================================================

find ./ -type f -iname "*.jpeg" -exec mogrify -verbose -format jpeg -layers Dispose -resize 1024\>x1024\> -quality 75% {} +
find ./ -type f -iname "*.jpg" -exec mogrify -verbose -format jpg -layers Dispose -resize 1024\>x1024\> -quality 75% {} +
find ./ -type f -iname "*.png" -exec mogrify -verbose -format png -alpha on -layers Dispose -resize 1024\>x1024\> {} +
