#!/bin/bash
# ==================================================================
# FILE     f_tmuxHelpers
# MACHINE  all
# INFO     various tmux helper functions
#
# DATE     09.10.2019
# OWNER    Bischofberger
# ==================================================================

# params: $1 = message to be shown
f_tmux_DisplayMessageAllClients(){
	local clientsList
	clientsList=$(tmux list-clients -F "#{client_tty}")
	readarray -t clientsArray <<<"$clientsList"
	for client in "${clientsArray[@]}" ; do
		tmux display-message -c "$client" "$1"
	done
}

f_tmux_ExportCurrentPath(){
  local currentPath
  local currentSession
  currentPath="$(pwd)"
  currentSession="$(tmux display-message -p "#S")"
  while [ -n "$1" ]; do
    case "$1" in
      "a"|"all")
        tmux list-windows -t "$currentSession" \
          | sed "/(active)/d" \
          | cut -d: -f1 \
          | xargs -I{} \
          tmux send-keys -t "$currentSession":{} "cd \"$currentPath\"" "Enter"
        shift;;
      *[0-9]*)
        tmux send-keys -t "$currentSession:$1" "cd \"$currentPath\"" "Enter"
        shift;;
      *)
        die "unknown parameter '$1'"
        ;;
    esac
  done
}

alias tmexp="f_tmux_ExportCurrentPath"
