#!/bin/bash
# ==================================================================
# FILE     mergemall
# MACHINE  all
# INFO     merges develop branches to master on all my repos
#
# DATE     13.08.2014
# OWNER    Bischofberger
# ==================================================================

#TODO:	- error handling

# my github repositories
declare -a Repo=(
    "$HOME/Dotfiles/" \
    "$HOME/Build/" \
    "$HOME/Scripts/" \
    "$HOME/Developer/C_C++/own/dwmstatus/" \
    "$HOME/Developer/Bash-and-Unix-Tools/own/musictogo/" \
)

die() {
    echo -e "$0: Error: $1" >&2
    exit 1
}

git_merge() {
	git checkout master
	git merge develop
	git checkout develop
}

# option for merging all repos at once
echo -n "want to merge develop branch with master in ALL repos? (y/n) "
read answer
case "$answer" in
	"y")
		ALL=true
		;;
	"n")
		ALL=false
		;;
	*)
		die "invalid input"
esac

# merge loop
for path in "${Repo[@]}" ; do
    cd $path
	if ( $ALL ) ; then
		pwd
		git_merge
	else
		echo -n "merge branch develop to master in $(pwd)? (y/n) "
		read answer
		case "$answer" in
			"y")
				git_merge
				;;
			"n")
				continue
				;;
			*)
				die "invalid input"
				;;
		esac
	fi

	echo ""
done

exit 0
