#!/bin/bash
# ==================================================================
# FILE     musicsync
# MACHINE  all
# INFO     USB-disks on Volumio have to be labeled as "Volumiodisk"
#
# DATE     08.12.2021
# OWNER    Bischofberger
# ==================================================================


# volumio
VOLUMIO1="192.168.178.29"
VOLUMIO2="192.168.178.45"
volumiodiskSSH="/mnt/USB/Volumiodisk/"

INCLUDEFILE="$HOME/Scripts/data/musicsync-inclexcl.txt"


die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}


# With $2 we can give rsync some extra options
syncto() {
  if [ -z "$INCLUDEFILE" ] ; then return 1 ; fi

  rsync -avu --delete $2 --include-from="$INCLUDEFILE" "$HOME/" $1 || return 1

  return 0
}


sshsync() {
  echo -n "syncto \"Volumio-balanced\" (1) or \"Volumio-revox\" (2)? "
  read answer

  if [[ $answer != 1 && $answer != 2 ]] ; then
    die "invalid option '$answer'"
  fi

  if [[ $answer == 1 ]] ; then syncto "--rsh=ssh volumio@$VOLUMIO1:$volumiodiskSSH" || die "something went wrong" ; fi
  if [[ $answer == 2 ]] ; then syncto "--rsh=ssh volumio@$VOLUMIO2:$volumiodiskSSH" || die "something went wrong" ; fi
}


usbsync() {
  source "$HOME/Scripts/f_diskscan"
  f_diskscan  # declares $CHOSEN_DISK

  if [ -n "$CHOSEN_DISK" ] ; then syncto "$CHOSEN_DISK" "--modify-window=1" || die "something went wrong" ; fi
}



#############################
## main script starts here ##
#############################

echo -n "USB (1) or SSH (2)? "
read number

case "$number" in
  "1")
    usbsync
    exit 0
    ;;
  "2")
    sshsync
    exit 0
    ;;
  *)
    die "invalid option '$number'"
    ;;
esac

