#!/bin/sh
# ==================================================================
# FILE     nmgui
# MACHINE  all
# INFO     Script to start and quit nm-applet within trayer
#          in order to manage network connections
# DEPENDS  trayer
#
# DATE     24.02.2014
# OWNER    Bischofberger
# ==================================================================

nm-applet	> /dev/null 2>/dev/null &
trayer		> /dev/null 2>/dev/null
killall nm-applet
