#!/bin/sh
# ==================================================================
# FILE     nmgui
# MACHINE  all
# INFO     Script to start and quit nm-applet within stalonetray
#          in order to manage network connections
# DEPENDS  stalonetray
#
# DATE     09.09.2015
# OWNER    Bischofberger
# ==================================================================

nm-applet	  > /dev/null 2>/dev/null &
stalonetray	> /dev/null 2>/dev/null
