#!/bin/bash
# ==================================================================
# FILE     pdfTojpg
# MACHINE  all
# INFO     convert multiple pages pdf to multiple jpg files (e.g. latex standalone to Word)
#          Standard density of 1200x1200
#
# DATE     28.01.2018
# OWNER    Bischofberger
# ==================================================================

DENSITY="1200"

die() {
	echo -e "$0: Error: $1" >&2
	exit 1
}

# no argument given
if [[ $# -ne 1 ]] ; then
	die "use: \"pdfTojpg [filename]\""
fi

# Imagemagick is buggy here. It takes up way too much RAM and density
# information is not stored within images.
#convert -density $DENSITY "${1}" "./${1%.pdf}.jpg"

# Therefore, let GhostScript handle it:
gs -o "./${1%.pdf}_%03d.png" -sDEVICE=png16m -r1200 "${1}"
