#!/bin/bash
# ==================================================================
# FILE     photomodelsort
# MACHINE  all
# INFO     This one puts all my messy RAW-files into seperate folders
#          of the form "CameraModel" according to their Model.
#          Makes use of exiftool.
#
# DATE     26.07.2021
# OWNER    Bischofberger
# ==================================================================

die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

for file in "$@" ; do
  if [ -f "$file" ] ; then
    MODEL="$(exiftool -Model "$file" | awk '{print $5; exit}')"
    echo "$file -> $MODEL"
    mkdir -p "$MODEL"
    mv "$file" "$MODEL"
  else
    die "$file is not a valid file"
  fi
done
