#!/bin/bash
# ==================================================================
# FILE     pullhemall
# MACHINE  all
# INFO     pulls all my git repositories at once
#
# DATE     16.06.2014
# OWNER    Bischofberger
# ==================================================================

declare -a Repo=(
    "$HOME/Dotfiles/" \
    "$HOME/Build/" \
)

die(){
    echo -e "$0: Error: $1" >&2
    exit 1
}

for path in "${Repo[@]}" ; do
    cd $path
    pwd
    git pull origin master || die "Could not pull."
done

exit 0
