#!/bin/bash
# ==================================================================
# FILE     screenshot
# MACHINE  all
# INFO     uses imagemagick to capture screenshots
#
# DATE     01.07.2016
# OWNER    Bischofberger
# ==================================================================
# TODO: add error handling

DIR="$HOME/Desktop"
FILE="screenshot"

cd $DIR

# Find the next number
NUM=$(ls $FILE-[0-9]*.jpg 2>/dev/null | sed -n '$ s/[^0-9]//gp' )
NUM=$( printf %03d $(expr $NUM + 1) )

import $FILE-$NUM.jpg

