#!/bin/bash
# ==================================================================
# FILE     skriptsplit
# MACHINE  all
# INFO     Split my school math theory script into chapters
#
# DATE     25.02.2022
# OWNER    Bischofberger
# ==================================================================

die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

# import chapter file
if [ -f "$1" ] ; then
  source "$1"
else
  die "missing or invalid argument"
fi

# check if variables are set in chapter file
if [ -z "${CHAPTERLIST+x}" ] || [ -z "${INPUTFILE+x}" ] || [ -z "${DESTFOLDER+x}" ] ; then
  die "given file is corrupted"
fi

mkdir -p "$DESTFOLDER"

# CHAPTERLIST comes in reversed order. So the last page of the current chapter
# (ENDOFCHAPTER) is given by the first page of the previous chapter in the list
# (which is actually the next one), minus one.
ENDOFCHAPTER=$(pdfinfo "$INPUTFILE" | awk '/'Pages:'/ {print $2}')

declare -n chapter

for chapter in "${CHAPTERLIST[@]}" ; do
  gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER \
     -dFirstPage=${chapter[1]} \
     -dLastPage=$ENDOFCHAPTER \
     -sOutputFile="${chapter[0]}" \
     "$INPUTFILE"

  (( ENDOFCHAPTER=${chapter[1]} - 1 ))
done

