#!/bin/bash
# ==================================================================
# FILE     snippy
# MACHINE  all
# INFO     mostly taken from: https://bbs.archlinux.org/viewtopic.php?id=71938&p=2
#          https://bbs.archlinux.org/viewtopic.php?id=71938
#          depends on: dmenu, xclip
#
# DATE     17.08.2016
# OWNER    Bischofberger
# ==================================================================

DIR=${HOME}/.snippy

cd ${DIR}

FILE=`find . -type f | grep -v '^\.$' | sed 's!\.\/!!' | /usr/bin/dmenu -b`

if [ -f ${DIR}/${FILE} ]; then
	xclip -i -selection primary < ${DIR}/${FILE}
	xclip -i -selection clipboard < ${DIR}/${FILE}
fi
