#!/bin/bash
# ==================================================================
# FILE     sortRAWsIntoFolders
# MACHINE  all
# INFO     This one puts all my messy RAW-files into seperate folders
#          of the form "year-month" according to their CreateDate.
#          Makes use of exiftool.
#
# DATE     01.05.2021
# OWNER    Bischofberger
# ==================================================================

die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

for file in "$@" ; do
  if [ -f "$file" ] ; then
    FULLDATE="$(exiftool -CreateDate "$file" | awk '{print $4; exit}')"
    YEAR="$(echo "$FULLDATE" | awk -F ":" '{print $1}')"
    MONTH="$(echo "$FULLDATE" | awk -F ":" '{print $2}')"
    FOLDER="$YEAR"-"$MONTH"
    echo "$file -> $FOLDER"
    mkdir -p "$FOLDER"
    mv "$file" "$FOLDER"
  else
    die "$file is not a valid file"
  fi
done
