#!/bin/bash
# ==================================================================
# FILE     statemall
# MACHINE  all
# INFO     show git status of all my git repositories at once
#					 ANSI escape sequences:
#					 Black        0;30     Dark Gray     1;30
#					 Red          0;31     Light Red     1;31
#					 Green        0;32     Light Green   1;32
#					 Brown/Orange 0;33     Yellow        1;33
#					 Blue         0;34     Light Blue    1;34
#					 Purple       0;35     Light Purple  1;35
#					 Cyan         0;36     Light Cyan    1;36
#					 Light Gray   0;37     White         1;37
#
# DATE     01.05.2017
# OWNER    Bischofberger
# ==================================================================

GitHubReposFile="$HOME/Scripts/data/GitHubRepos.txt"
LocalReposFile="$HOME/Scripts/data/LocalRepos.txt"
COLOR1='\033[1;31m'
COLOR2='\033[1;35m'
NC='\033[0m'  # No Color

# arg1: ReposFile
# arg2: Color
printRepos(){
  mapfile -t Repos <$1

  echo -e "${2}--------------------------------------------${NC}"
  for path in "${Repos[@]}" ; do
    eval cd $path
    echo -e ${2}`pwd`${NC}
    echo "---------"
    git branch
    echo "---------"
    git status
    echo -e "${2}--------------------------------------------${NC}"
  done

}

echo -e "${COLOR1}=============${NC}"
echo -e "${COLOR1}GitHub repos:${NC}"
echo -e "${COLOR1}=============${NC}"
printRepos $GitHubReposFile $COLOR1

echo -e "\n"

echo -e "${COLOR2}============${NC}"
echo -e "${COLOR2}Local repos:${NC}"
echo -e "${COLOR2}============${NC}"
printRepos $LocalReposFile $COLOR2

exit 0
