#!/bin/bash
# ==================================================================
# FILE     statemall
# MACHINE  all
# INFO     show git status of all my git repositories at once
#
# DATE     03.03.2016
# OWNER    Bischofberger
# ==================================================================

GitHubReposFile="$HOME/Scripts/data/GitHubRepos.txt"

# my github repositories
mapfile -t Repos <$GitHubReposFile

for path in "${Repos[@]}" ; do
	eval cd $path
	pwd
	git status
	echo "--------------"
done

exit 0
