#!/bin/bash
# ==================================================================
# FILE     tikzextract
# MACHINE  all
# INFO     - Extract all tikzpictures of a bunch of tex files 
#            and put them in a latex standalone file ($OUTFILE).
#          - Compile it with latexmk (use -c option).
#
#          To include all .tex files in some folder structure, just do:
#          "find -name "*.tex" | tikzextract
#
# DATE     26.04.2022
# OWNER    Bischofberger
# ==================================================================

OUTDIR="tikzextract_out"
OUTFILE="tikzextract.tex"


die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}


beginOutputfile() {
  mkdir -p "$OUTDIR" || die "couldn't create outdir"

  cat > "$OUTDIR/$OUTFILE" <<'EOF'
% ==================================================================
% FILE     tikzextract.tex
% INFO     temporary file for tikzextract script
% ==================================================================

% temporary standalone-luatex fix
\RequirePackage{luatex85}

\documentclass[10pt,tikz]{standalone}

% fonts
\usepackage[T1]{fontenc}
\usepackage[utf8x]{inputenc}
\usepackage[ngerman]{babel}
\usepackage{lmodern}

% math
\usepackage{mathtools}
\usepackage{amssymb}

% units
\usepackage{siunitx}
\sisetup{per-mode=symbol}

\usepackage{myMacrosMath}
\usepackage{myMacrosMisc}
\usepackage{tikzStyle}
\usepackage{tikzCollection}
\usepackage{tikz3dStyle}
\usepackage{pgfplotsStyle}
\usepackage{pgfplotsCollection}
\usetikzlibrary{matrix,shapes.geometric,patterns,decorations.pathreplacing}


\begin{document}

% ---------------------------------------------------------------------------------------------------------------

% TODO: manually include all newcommands, \SetStdMainCoords, \pgfdeclarelayer{...}, \pgfplotsset{...} etc. here!
% ...
% ...

% ---------------------------------------------------------------------------------------------------------------


EOF
}


endOutputfile() {
  echo -e "\\\end{document}" >>"$OUTDIR/$OUTFILE"
  vim -c "setf=tex | execute 'normal! gg=G' | update | quitall" "$OUTDIR/$OUTFILE"  # use vim to indent file
}


extractTikZ() {
  if [[ ! -f "$1" ]] || [[ "$1" = *"$OUTFILE" ]] ; then
    return 1  # return "false", do nothing
  fi
  echo -n "extracting tikz from $1..."
  local begin_pattern="\\\begin{tikzpicture}"
  local end_pattern="\\\end{tikzpicture}"
  local docname_node="\\\node[below=10pt,font=\\\small\\\itshape] at (current bounding box.south) {($1)};\n"
  awk '/'"$begin_pattern"'/ {f=1}
       f                    {if(/'"$end_pattern"'/) {f=0; print "'"$docname_node$end_pattern"'\n"} else {print}}' "$1" >>"$OUTDIR/$OUTFILE"
  #awk '/\\begin{tikzpicture}/{f=1} f{print; if(/\\end{tikzpicture}/) {f=0; print ""}}' "$1" >>"$OUTDIR/$OUTFILE"
  echo "done."
}


compile() {
  cd "$OUTDIR" || die "couldn't change directory to \"$OUTDIR\""
  latexmk -pdf -interaction=nonstopmode -file-line-error "$1"
}



# ========================================================
# main routine

# check for the compile-option
if [[ "$1" == "-c" ]] || [[ "$1" == "--compile" ]] ; then
  compile "$OUTFILE"
  exit 0
fi

beginOutputfile

# read from stdin if no argument is given
if [ -z "$1" ] ; then
  while read -r line ; do   # read from stdin
    extractTikZ "$line"
  done
else
  for texfile in "$@" ; do  # loop over argument list
    extractTikZ "$texfile"
  done
fi

endOutputfile

