#!/bin/bash
# ==================================================================
# FILE     trash
# MACHINE  all
# INFO     moves files and folders to ~/.trash instead of 
#          deleting them
#
# DATE     25.06.2014
# OWNER    Bischofberger
# ==================================================================

TRASH="/home/$(hostname)/.trash"

die() {
    echo -e "$0: Error: $1" >&2
    exit 1
}

if [ -z "$1" ] ; then
    ls --color=auto $TRASH
fi

# if first argument is "-e", then empty
if [[ $1 == -e ]] || [[ $1 == --empty ]] ; then
    echo -n "Do you really want to empty the trash? (y/n) "
    read answer
    if [[ $answer == y ]] ; then
        rm -r $TRASH  || die "Could not empty trash."
        mkdir $TRASH
        # do not let the owner of .trash/ be "root"
        chown "$(users):users" $TRASH
        echo "trash is empty."
    else
        echo "Nothing done."
    fi
    exit
fi

# move all arguments to $TRASH if possible
mkdir -p $TRASH
chown "$(users):users" $TRASH

for file in "$@" ; do
    if [[ $file == -* ]] ; then  # arguments beginning with "-" are invalid
        echo "invalid argument: $file."
        continue
    fi

    # add prefixes
    prefix=""
    while [ -e "$TRASH/$prefix$file" ] || [ -d "$TRASH/$prefix$file" ] ; do
        prefix="_$prefix"
    done
    
    mv -v "$file" "$TRASH/$prefix$file"
done
