#!/bin/bash
# ==================================================================
# FILE     trash
# MACHINE  all
# INFO     moves files and folders to ~/.trash instead of 
#          deleting them
#
# DATE     04.06.2017
# OWNER    Bischofberger
# ==================================================================

TRASH="/home/$(hostname)/.trash"

die() {
	echo -e "$0: Error: $1" >&2
	exit 1
}

# Check if $TRASH folder already exists. If not, create one.
# Avoid creating $TRASH folder as root.
if [ ! -d $TRASH ] ; then
	echo "$TRASH/ folder not available."

	if [[ $EUID -eq 0 ]] ; then
		die "Your are root. Either run as non-root or create $TRASH folder manually."
	fi

	echo "Creating empty folder: $TRASH".
	mkdir $TRASH
fi

# If no argument is given, show content of .trash/ folder.
if [ -z "$1" ] ; then
	ls --color=auto $TRASH
	exit
fi

# If first argument is "-e", then empty.
if [[ $1 == -e ]] || [[ $1 == --empty ]] ; then
	echo -n "Do you really want to empty the trash? (y/n) "
	read answer

	if [[ $answer == y ]] ; then
		rm -rf $TRASH/*  || die "Could not empty trash."
		echo "Trash is empty."
	else
		echo "Nothing done."
	fi

	exit
fi

# Move all arguments to $TRASH if possible.
for data in "$@" ; do
	if [[ $data == -* ]] ; then  # arguments beginning with "-" are invalid
		echo "Invalid argument: $data"
		continue
	fi

	# Add postfix to duplicates.
	postfix=""
	while [ -e "$TRASH/$data$postfix" ] || [ -d "$TRASH/$data$postfix" ] ; do
		postfix+="_"
	done

	mv -v "$data" "$TRASH/$data$postfix"
done
