#!/bin/bash
# ==================================================================
# FILE     trash
# MACHINE  all
# INFO     moves files and folders to ~/.trash instead of 
#          deleting them
#
# DATE     15.05.2014
# OWNER    Bischofberger
# ==================================================================

TRASH="/home/$(hostname)/.trash"

die() {
    echo -e "$0: Error: $1" >&2
    exit 1
}

if [ -z "$1" ] ; then
    die "use with arguments."
fi

# if first argument is "-e", then empty
if [[ $1 == -e ]] || [[ $1 == --empty ]] ; then
    echo -n "Do you really want to empty the trash? (y/n) "
    read answer
    if [[ $answer == y ]] ; then
        rm -r $TRASH
        mkdir $TRASH
        echo "trash is empty."
    else
        echo "Nothing done."
    fi
    exit
fi

# move all arguments to $TRASH if possible
mkdir -p $TRASH

for file in "$@" ; do
    if [[ $file == -* ]] ; then  # arguments beginning with "-" are invalid
        echo "invalid argument: $file."
        continue
    fi
    if [ -e "$TRASH/$file" ] || [ -d "$TRASH/$file" ] ; then  # file/dir exists, give it a new name
        mv -v "$file" "$TRASH/_$file"
    else
        mv -v "$file" "$TRASH/"
    fi
done
