#!/bin/env bash
# ==================================================================
# FILE     vimserv  
# MACHINE  all
# INFO     open files from ranger in one vim server
#          edit .config/ranger/rifle $EDITOR line...
#          uses tmux
#
# DATE     04.06.2014
# OWNER    Bischofberger
# ==================================================================


SERVER_ID="VIMSERV"
TAB=""

die() {
    echo -e "$0: Error: $1" >&2
    exit 1
}

# run it with/without arguments
if [ -z "$1" ] ; then
    # only one server should be running at the same time
    serverlist=`vim --serverlist | grep $SERVER_ID`
    if [ $serverlist ] ; then
        die "vimserv server already running."
    fi

    # rename tmux window
    tmux rename-window vimserv

    # start the vim server
    vim --servername $SERVER_ID  || die "Could not start vim server."
else
    serverlist=`vim --serverlist | grep $SERVER_ID`
    if [ -z $serverlist ] ; then
        die "Need to start a vim server first by running \"vimserv\"."
    fi

    # set -tab option to open files in new tabs
    if [[ $1 == --tabe ]] ; then
        TAB="-tab"
        shift
    fi

    for file in "$@" ; do
        vim --servername $SERVER_ID --remote$TAB "$file" \
            || die "could not attach to vim server."
    done
fi
