#!/bin/bash
# ==================================================================
# FILE     vol2
# MACHINE  all
# INFO     just some pamixer (pulseaudio) wrapper
#          requires pamixer package
#
# DATE     11.06.2019
# OWNER    Bischofberger
# ==================================================================

die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

# get volume and state [on|off]
getMixerStatus() {
  echo -e -n "current volume: "
  pamixer --get-volume
  echo -e -n "mute: "
  pamixer --get-mute
}

# main -------------------------------------------------

# no argument gives info
if [ -z "$1" ] ; then
  getMixerStatus
  exit 0
fi

# toggle mute, increase, decrease
case "$1" in
  "t")
    pamixer --toggle-mute
    exit 0
    ;;
  "on"|"unmute"|"um")
    pamixer --unmute
    exit 0
    ;;
  "off"|"mute"|"m")
    pamixer --mute
    exit 0
    ;;
  "+")
    pamixer --increase 10
    exit 0
    ;;
  "-")
    pamixer --decrease 10
    exit 0
    ;;
  *)
    ;;
esac

# set volume
pamixer --set-volume "$1"
