#!/bin/bash
# ==================================================================
# FILE     volumiosync
# MACHINE  all
# INFO     USB-disks on Volumio have to be labeled as "Volumiodisk"
#
# DATE     10.04.2019
# OWNER    Bischofberger
# ==================================================================

INCLUDEFILE="$HOME/Scripts/data/volumiosync-inclexcl.txt"

die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

syncto() {
  rsync -avu --delete --include-from="$INCLUDEFILE" "$HOME/" $1 || die "couldn't sync"
}

sshsync() {
  echo -n "syncto \"Volumio-balanced\" (1) or \"Volumio-revox\" (2)? "
  read answer

  if [[ $answer != 1 && $answer != 2 ]] ; then die "invalid option '$answer'" ; fi

  local VOLUMIO1="192.168.178.29"
  local VOLUMIO2="192.168.178.45"
  local volumiodiskSSH="/mnt/USB/Volumiodisk/"

  if [[ $answer == 1 ]] ; then syncto "--rsh=ssh volumio@$VOLUMIO1:$volumiodiskSSH" ; fi
  if [[ $answer == 2 ]] ; then syncto "--rsh=ssh volumio@$VOLUMIO2:$volumiodiskSSH" ; fi
}

usbsync() {
  local volumiodiskUSB="/run/media/desktop/Volumiodisk/"
  syncto "$volumiodiskUSB"
}


#############################
## main script starts here ##
#############################

echo -n "SSH (1) or USB (2)? "
read number

case "$number" in
  "1")
    sshsync
    exit 0
    ;;
  "2")
    usbsync
    exit 0
    ;;
  *)
    die "invalid option '$number'"
    ;;
esac

