#!/bin/bash
# ==================================================================
# FILE     zathuratab.sh
# MACHINE  all
# INFO     - open pdfs in zathura within tabbed
#          - for use with ranger: 
#            add zathuratab in ~/.config/ranger/rifle.conf
#          - for use with vim netrw (x command): 
#            use "xdg-mime default zathuratab.desktop application/pdf"
#
# DATE     22.07.2016
# OWNER    Bischofberger
# ==================================================================

# variables
tempfile=/tmp/tabbed.xid


if [ "$(pidof tabbed)" ] && [ "$(pidof zathura)" ] ; then  # tabbed and zathura already running
  for file in "$@" ; do
    if [ -n "$file" ] ; then
      zathura --fork -e $(<$tempfile) "$file"
    else
      zathura --fork -e $(<$tempfile)
    fi
  done
else
  tabbed -c -d >$tempfile
  for file in "$@" ; do
    if [ -n "$file" ] ; then
      zathura --fork -e $(<$tempfile) "$file"
    else
      zathura --fork -e $(<$tempfile)
    fi
  done
fi
