#!/bin/bash
# ==================================================================
# FILE     zathuratab.sh
# MACHINE  all
# INFO     - open pdfs in zathura within tabbed
#          - for use with ranger: 
#            add zathuratab in ~/.config/ranger/rifle.conf
#          - for use with vim netrw (x command): 
#            use "xdg-mime default zathuratab.desktop application/pdf"
#
# DATE     01.05.2016
# OWNER    Bischofberger
# ==================================================================

# variables
tempfile=/tmp/tabbed.xid


if [ "$(pidof tabbed)" ] && [ "$(pidof zathura)" ] ; then  # tabbed and zathura already running
    if [ -n "$1" ] ; then
        zathura --fork -e $(<$tempfile) "$1"
    else
        zathura --fork -e $(<$tempfile)
    fi
else
    tabbed -c -d >$tempfile
    if [ -n "$1" ] ; then
        zathura --fork -e $(<$tempfile) "$1"
    else
        zathura --fork -e $(<$tempfile)
    fi
fi
