#!/bin/bash
# ==================================================================
# FILE     pullhemall
# MACHINE  all
# INFO     pulls all my git repositories at once
#
# DATE     26.08.2014
# OWNER    Bischofberger
# ==================================================================

BRANCHES="master develop"

declare -a Repo=(
    "$HOME/Dotfiles/" \
    "$HOME/Build/" \
)

for path in "${Repo[@]}" ; do
    cd $path
    pwd
    git pull origin ${BRANCHES}
		echo ""
done

exit 0
