#!/bin/bash
# ==================================================================
# FILE     pushemall
# MACHINE  all
# INFO     pushes all my git repositories at once
#
# DATE     16.07.2014
# OWNER    Bischofberger
# ==================================================================

# my github repositories
declare -a Repo=(
    "$HOME/Dotfiles/" \
    "$HOME/Build/" \
    "$HOME/Scripts/" \
    "$HOME/Developer/C_C++/own/dwmstatus/" \
    "$HOME/Developer/Bash-and-Unix-Tools/own/musictogo/" \
)

die(){
    echo -e "$0: Error: $1" >&2
    exit 1
}

for path in "${Repo[@]}" ; do
    cd $path
    pwd
    git push --all
		echo ""
done

exit 0
