#!/bin/bash
# ==================================================================
# FILE     albumartinflac
# MACHINE  all
# INFO     - includes albumart in .flac files
#          - uses "metaflac" program, see:
#            https://www.xiph.org/flac/documentation_tools_metaflac.html
#          - How it works:
#            1.) save album cover as "cover.jpg" in album folder
#            2.) run albumartinflac /path/to/album/
#          - if you have file containing a list of album folder paths
#            you can simply do a:
#            while read line ; do ./albumartinflac "$line"; done < albumlist
#
# DATE     01.07.2014
# OWNER    Bischofberger
# ==================================================================

die() {
    echo -e "$0: Error: $1" >&2
    exit 1
}

# no arguments given
if [ -z "$1" ] ; then
    die "Path to album folder needed as argument."
fi

START=`pwd`

# loop over argument list
for album in "$@" ; do
    cd "$START"

    # wrong argument
    if [ ! -d "$album" ] ; then
        echo "Not a valid path. Skipping $album"
        continue
    fi

    albumpath="$1"

    # if last character is a "/", then remove it
    if [[ $album == */ ]] ; then
        albumpath="${album%?}"
    fi

    # check if "cover.jpg" exists
    if [ ! -e "$albumpath/cover.jpg" ] ; then
        echo "No cover.jpg found. Skipping $albumpath"
        continue
    fi

    # -------------------------------------
    # everything ok up to here, do the work
    # -------------------------------------
    echo "next album: $albumpath..."
    cd "$albumpath/"

    shopt -s nullglob
    for track in *.flac ; do
        echo "uploading albumcover to $track"

        # remove existing images
        metaflac --remove --block-type=PICTURE "$track"

        # add image to track
        metaflac --import-picture-from="|image/jpeg|||./cover.jpg" "$track"
    done

    echo "...done."
done
