#!/bin/bash
# ==================================================================
# FILE     abookExport
# MACHINE  all
# INFO     export abook to fastmail
#
# DATE     17.08.2016
# OWNER    Bischofberger
# ==================================================================

abook --convert \
      --informat abook --infile ~/.abook/addressbook \
      --outformat vcard --outfile addressbookFromAbook.vcf
