#!/bin/bash
# ==================================================================
# FILE     abookGroups
# MACHINE  all
# INFO     extract group members of abook addressbook
#
# DATE     17.08.2016
# OWNER    Bischofberger
# ==================================================================

ADDRESSBOOK="$HOME/.abook/addressbook"
GROUP=()
BLOCKLIST=()
COL_EMAIL_ADR=""

die() {
  echo -e "$0: Error: $1" >&2
  exit 1
}

# read argument list (= group names)
for pattern in "$@" ; do
  GROUP+=("$pattern")
done

# read blocks
{
  read -r block    # First line only
  while read -r; do
    if [[ $REPLY =~ ^$ ]]; then
      # Do what you like with the contents 
      # $block here, then ...
      BLOCKLIST+=("$block")
      block=""
    else
      block+="$REPLY"$'\n'  # $'\n' means: "insert a new line" (bash and zsh only)
    fi
  done
} < "$ADDRESSBOOK"

BLOCKLIST=("${BLOCKLIST[@]:1,3}") #removed the 1st 3 elements

for block in "${BLOCKLIST[@]}" ; do
  for group in "${GROUP[@]}" ; do
    echo "$block" | awk -F "=|," '$1 == "group" && /'"$group"'/ {exit 1}'
    HAS_GROUP=$?  # $? is the exit status of the last statement
    if [ $HAS_GROUP -eq 1 ] ; then
      COL_EMAIL_ADR+=$(echo "$block" | awk -F "=" '$1 == "email" {print $2", "}')
      break  # inner loop
    fi
  done
done

echo -n "$COL_EMAIL_ADR" | xclip -i -selection primary
echo -n "$COL_EMAIL_ADR" | xclip -i -selection clipboard
