#!/bin/bash
# ==================================================================
# FILE     clipswap
# MACHINE  all
# INFO     uses xclip to swap PRIMARY and CLIPBOARD
#
# DATE     17.08.2016
# OWNER    Bischofberger
# ==================================================================

die() {
	echo -e "$0: Error: $1" >&2
	exit 1
}

clearSelection() {  # arg: primary/secondary/clipboard
  xclip -i -selection "$1" /dev/null
}

listContent() {
	echo -e "[[PRIMARY]]------------------------" 
	xclip -o -selection primary 2>/dev/null ; echo ""

	echo -e "[[CLIPBOARD]]----------------------"
	xclip -o -selection clipboard 2>/dev/null ; echo ""

	echo -e "[[SECONDARY]]----------------------"
	xclip -o -selection secondary 2>/dev/null ; echo ""
}

swapThem() {
	# step 1 - copy PRIMARY to SECONDARY
	xclip -o -selection primary 2>/dev/null | xclip -i -selection secondary
	# step 2 - copy CLIPBOARD to PRIMARY
	xclip -o -selection clipboard 2>/dev/null | xclip -i -selection primary
	# step 3 - copy SECONDARY (former PRIMARY) to CLIPBOARD
	xclip -o -selection secondary 2>/dev/null | xclip -i -selection clipboard
	# step 4 - clear SECONDARY
  clearSelection "secondary"
}

clearAll() {
  clearSelection "primary"
  clearSelection "secondary"
  clearSelection "clipboard"
}

# if no argument is given, swap contents of PRIMARY/CLIPBOARD
if [ -z "$1" ] ; then
	swapThem
	exit 0
fi

# various options
case "$1" in
	"-s"|"--show")
		listContent
		exit 0
		;;
	"-c"|"--clear")
		clearAll
		;;
	*)
		die "invalid argument"
		;;
esac
