#!/bin/bash
# ==================================================================
# FILE     dwm-statusbar.sh
# MACHINE  all
# INFO     Status script for dwm
#          clock and date is being shown by tmux on the right bottom
#
# DATE     03.03.2014
# OWNER    Bischofberger
# ==================================================================


bat(){
  onl="$(grep "on-line" <(acpi -V))"
  charge="$(awk '{print +$4}' <(acpi -b))"
  if [[ ( -z $onl && $charge -gt 20 ) ]]; then 
      echo "BAT $charge%"
  elif [[ ( -z $onl && $charge -le 20 ) ]]; then
      echo "BAT $charge%"
  else
      echo "AC $charge%"
  fi
}

vol(){
  vol="$(awk '/%/ {gsub(/[\[\]]/,""); print $4}' <(amixer get Master))"
  on_off="$(awk '/%/ {gsub(/[\[\]]/,""); print $6}' <(amixer get Master))"
  if [ $on_off == on ]; then
      echo "VOL $vol"
  else
      echo "MUTE"
  fi
}

xsetroot -name "[$(bat)] [$(vol)] "



#dte(){
#  date +"%d.%b %Y - %H:%M"
#}

# Pipe to status bar
#if [[ $(hostname) == "laptop" ]] ; then
#    xsetroot -name "[$(bat)] [$(vol)] $(dte) Uhr "
#else
#    xsetroot -name "$(dte) Uhr "
#fi
