#!/bin/bash
# ==================================================================
# FILE     mailtab
# MACHINE  all
# INFO     opens mutt and mbsync secure in a tabbed environment, 
#          instead of a tmux session
# DEPENDS  suckless tabbed
#
# DATE     24.02.2014
# OWNER    Bischofberger
# ==================================================================

tabbed -c -r 2 st -w '' -t mail -f -*-terminus-medium-r-*-*-16-*-*-*-*-*-*-*
