#!/usr/bin/env bash
# ==================================================================
# FILE     backup
# MACHINE  desktop
# INFO     rsnapshot wrapper
#
# DATE     07.11.2022
# OWNER    Bischofberger
# ==================================================================

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

CONFIGS="/home/desktop/Scripts/data"

rsnapshot -c "$CONFIGS/rsnapshot_local.conf" "alpha"
