#!/bin/bash
# ==================================================================
# FILE     pushemall
# MACHINE  all
# INFO     pushes all my git repositories at once
#
# DATE     17.10.2018
# OWNER    Bischofberger
# ==================================================================

GitHubReposFile="$HOME/Scripts/data/GitOnGitHub.txt"

# my github repositories
mapfile -t Repos <$GitHubReposFile

for path in "${Repos[@]}" ; do
	eval cd $path
	pwd
	git push --all
	echo ""
done

exit 0
