#!/bin/bash
# ==================================================================
# FILE     snippy
# OS       linux
# MACHINE  all (wayland)
# INFO     mostly taken from: https://bbs.archlinux.org/viewtopic.php?id=71938&p=2
#          https://bbs.archlinux.org/viewtopic.php?id=71938
#          depends on: wmenu, wl-clipboard
#
# DATE     11.06.2025
# OWNER    Bischofberger
# ==================================================================

DIR=${HOME}/vimsnippy

cd "${DIR}" || exit 1

FILE=$(find . -type f | grep -v '^\.$' | sed 's!\.\/!!' | sort | /usr/bin/wmenu -b)

if [ -f "${DIR}/${FILE}" ]; then
	wl-copy < "${DIR}/${FILE}"
  exit 0  # 0 = success
fi

exit 1
