#!/bin/bash
# ==================================================================
# FILE     statemall
# MACHINE  all
# INFO     show git status of all my git repositories at once
#					 ANSI escape sequences:
#					 Black        0;30     Dark Gray     1;30
#					 Red          0;31     Light Red     1;31
#					 Green        0;32     Light Green   1;32
#					 Brown/Orange 0;33     Yellow        1;33
#					 Blue         0;34     Light Blue    1;34
#					 Purple       0;35     Light Purple  1;35
#					 Cyan         0;36     Light Cyan    1;36
#					 Light Gray   0;37     White         1;37
#
# DATE     04.10.2018
# OWNER    Bischofberger
# ==================================================================

GitPathLists="$HOME/Scripts/data/"
GitOnGitHubFile="GitOnGitHub.txt"
GitOnLocalFile="GitOnLocal.txt"
GitInactiveFile="GitInactive.txt"
COLOR1='\033[1;31m'
COLOR2='\033[1;35m'
COLOR3='\033[1;30m'
NC='\033[0m'  # No Color

die() {
	echo -e "$0: Error: $1" >&2
	exit 1
}

# arg1: ReposFile
# arg2: Color
printRepos(){
  mapfile -t Repos <$1

  echo -e "${2}--------------------------------------------${NC}"
  for path in "${Repos[@]}" ; do
    eval cd $path
    echo -e ${2}`pwd`${NC}
    echo "---------"
    git branch
    echo "---------"
    git status
    echo -e "${2}--------------------------------------------${NC}"
  done

}


# ---- main routine ----

# no argument given
if [ -z "$1" ] ; then
  echo -e "${COLOR1}=============${NC}"
  echo -e "${COLOR1}GitHub repos:${NC}"
  echo -e "${COLOR1}=============${NC}"
  printRepos "$GitPathLists$GitOnGitHubFile" "$COLOR1"

  echo -e "\n"

  echo -e "${COLOR2}============${NC}"
  echo -e "${COLOR2}Local repos:${NC}"
  echo -e "${COLOR2}============${NC}"
  printRepos "$GitPathLists$GitOnLocalFile" "$COLOR2"

  exit 0
fi

# various options
case "$1" in
  "-i"|"--inactive")
    echo -e "${COLOR3}===============${NC}"
    echo -e "${COLOR3}Inactive repos:${NC}"
    echo -e "${COLOR3}===============${NC}"
    printRepos "$GitPathLists$GitInactiveFile" "$COLOR3"
    exit 0
    ;;
  *)
    die "invalid argument"
    ;;
esac

exit 0
